version: '3.8'

services:
  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"

  manager:
    build:
      context: .
      dockerfile: Dockerfile_manager
    volumes:
      - data_volume:/data
    depends_on:
      - rabbitmq
    ports:
      - "8000:8000"

  worker:
    build:
      context: .
      dockerfile: Dockerfile_worker
    volumes:
      - data_volume:/data
    depends_on:
      - rabbitmq

volumes:
  data_volume:
