


FROM python:3.12-slim

WORKDIR /app/manager

COPY ./app/manager/requirements_manager.txt ./
RUN pip install --no-cache-dir -r requirements_manager.txt

COPY ./app/manager /app/manager

EXPOSE 8000
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
