


FROM python:3.10-slim

WORKDIR /app/ai_1

RUN apt-get update && apt-get install -y \
    libopencv-dev \
    libgl1-mesa-glx \
    ffmpeg \
    curl \
    && rm -rf /var/lib/apt/lists/*

COPY ./app/ai_1/requirements_worker.txt .

RUN pip install --upgrade pip && \
    pip install --no-cache-dir -r requirements_worker.txt
COPY ./app/ai_1 /app/ai_1

CMD ["celery", "-A", "worker", "worker", "--loglevel=info"]
