version: '3.8'

services:
  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"
  
  manager:
    build:
      context: .
      dockerfile: Dockerfile_manager
    volumes:
      - videos_volume:/data/uploads/videos
      - images_volume:/data/uploads/images
      - results_volume:/data/results
    depends_on:
      - rabbitmq
    ports:
      - "8000:8000"

  worker:
    build:
      context: .
      dockerfile: Dockerfile_worker
    volumes:
      - videos_volume:/data/uploads/videos
      - images_volume:/data/uploads/images
      - results_volume:/data/results
    depends_on:
      - rabbitmq

volumes:
  videos_volume:
  images_volume:
  results_volume:
