


FROM python:3.12-slim

WORKDIR /app/ai_1

COPY ./app/ai_1/requirements_worker.txt ./
RUN pip install --no-cache-dir -r requirements_worker.txt

COPY ./app/ai_1 /app/ai_1

CMD ["celery", "-A", "worker", "worker", "--loglevel=info"]
